import { StyleSheet } from "react-native";

export default StyleSheet.create({
  addressActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    marginRight: 8,
  },
  addressActionText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "black",
    marginLeft: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#00000099",
  },
  modalCard: {
    backgroundColor: "white",
    margin: 20,
    padding: 20,
    borderRadius: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#D3D3D3",
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "gray",
    borderRadius: 10,
  },
  cancelBtnText: {
    color: "white",
    fontWeight: "bold",
  },
  saveBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#C67C4E",
    borderRadius: 10,
  },
  saveBtnText: {
    color: "white",
    fontWeight: "bold",
  },
  productCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    padding: 15,
    borderRadius: 12,
    backgroundColor: "white",
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
  },
  productDesc: {
    fontSize: 14,
    color: "gray",
  },
  qtyRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  qtyButton: {
    width: 35,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D3D3D3",
  },
  qtyText: {
    fontSize: 16,
    fontWeight: "bold",
    marginHorizontal: 15,
  },
  stockWarning: {
    color: "red",
    fontSize: 12,
    textAlign: "center",
    marginTop: 10,
  },
  discountCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#C67C4E",
    paddingVertical: 38,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginTop: 20,
  },
  discountText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    flex: 1,
    marginLeft: 12,
  },
  discountDots: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 5,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 20,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  summaryText: {
    fontSize: 16,
    color: "black",
  },
  summaryTextBold: {
    fontSize: 16,
    fontWeight: "bold",
    color: "black",
  },
  summaryTotal: {
    borderTopWidth: 1,
    paddingTop: 10,
  },
  orderBtnWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  orderButton: {
    backgroundColor: "#C67C4E",
    paddingVertical: 12,
    height: 55,
    marginTop: 20,
    width: "80%",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  orderBtnText: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
  },
});
