import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  keyboardContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    backgroundColor: 'black',
    padding: 20,
  },
  container: {
    width: "100%",
    alignItems: 'center',
    backgroundColor: 'black',
    padding: 20,
    borderRadius: 10,
  },
  title: {
    fontSize: 38,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 35,
  },
  input: {
    width: '100%',
    height: 55,
    backgroundColor: '#333',
    borderRadius: 10,
    marginTop: 20,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#666',
    color: 'white',
  },
  phoneContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    backgroundColor: '#333',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#666',
    marginTop: 20,
    marginBottom: 15,
  },
  countryPicker: {
    padding: 15,
    borderRightWidth: 1,
    borderColor: '#666',
  },
  countryText: {
    color: 'white',
    fontSize: 16,
  },
  phoneInput: {
    flex: 1,
    height: 55,
    paddingHorizontal: 10,
    color: 'white',
  },
  pickerContainer: {
    width: '100%',
    height: 55,
    marginTop: 20,
    backgroundColor: '#333',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#666',
    justifyContent: 'center',
    marginBottom: 15,
  },
  picker: {
    color: 'white',
    width: '100%',
  },
  submitButton: {
    width: '100%',
    height: 55,
    backgroundColor: '#C67C4E',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginTop: 20,
    marginBottom: 15,
  },
  submitText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loginText: {
    color: 'white',
    fontSize: 14,
  },
});
