import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("screen");

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FB" },
  map: { flex: 1 },
  infoContainer: {
    backgroundColor: "white",
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    position: "absolute",
    bottom: 0,
    width: "100%",
    elevation: 10,
  },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  timeText: { fontSize: 22, fontWeight: "bold" },
  addressText: { fontSize: 16, marginBottom: 10 },
  bold: { fontWeight: "bold" },
  progressContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  progressBar: {
    flex: 1,
    height: 6,
    backgroundColor: "#ddd",
    marginHorizontal: 2,
    borderRadius: 3,
  },
  completed: { backgroundColor: "#4CAF50" },
  incomplete: { backgroundColor: "#ddd" },
  statusBoxWrapper: {
    flexDirection: "row",
    padding: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    backgroundColor: "white",
    borderRadius: 15,
    marginTop: 20,
    alignItems: "center",
    marginBottom: 15,
  },
  statusImage: { width: 35, height: 35, borderRadius: 8 },
  statusTextWrapper: { marginLeft: 15 },
  statusTitle: { fontSize: 19, fontWeight: "bold" },
  statusDesc: { fontSize: 16, color: "gray" },
  courierBox: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  boxAvatar: { width: 50, height: 50, borderRadius: 5, marginRight: 10 },
  courierName: { fontSize: 16, fontWeight: "bold" },
  courierRole: { fontSize: 14, color: "gray" },
  callButton: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "gray",
  },
  startButtonWrapper: { position: 'absolute', bottom: 100, right: 20 },
  startButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: "center",
  },
  startButtonText: { color: 'white', fontWeight: 'bold' },
});
